//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Area.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceCheckInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceCheckInfo()
        {
            this.VisitPlaces = new HashSet<VisitPlace>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string CheckinLatitude { get; set; }
        public string CheckinLongitude { get; set; }
        public string CheckoutLatitude { get; set; }
        public string CheckoutLongitude { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitPlace> VisitPlaces { get; set; }
    }
}
