//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Area.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorVisitPlaceComment
    {
        public int ID { get; set; }
        public Nullable<bool> PlaceOwner { get; set; }
        public int SupervisorVisitPlaceID { get; set; }
        public int RaitingID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> RaitingStar { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual RaitingQuestion RaitingQuestion { get; set; }
        public virtual SupervisorVisitPlace SupervisorVisitPlace { get; set; }
    }
}
