//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Area.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogInformation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime ProcessingTime { get; set; }
        public int ProcessingTypeId { get; set; }
    
        public virtual ProcessingType ProcessingType { get; set; }
        public virtual User User { get; set; }
    }
}
