//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Area.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitPlaceCarInfo
    {
        public int ID { get; set; }
        public int VisitPlaceID { get; set; }
        public int RentACarID { get; set; }
        public string CarReceivePoint { get; set; }
        public string CarDeliveryPoint { get; set; }
        public Nullable<System.DateTime> CarReceiveDate { get; set; }
        public Nullable<System.DateTime> CarDeliveryDate { get; set; }
        public string CarBrandName { get; set; }
        public string CarModelName { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public string CheckinLatitude { get; set; }
        public string CheckinLongitude { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual RentACar RentACar { get; set; }
        public virtual VisitPlace VisitPlace { get; set; }
    }
}
